org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
loader_version_range=[1,)

mod_id=dungeons_controls
mod_name=Dungeons Controls
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.yyz.controls
mod_authors=yyz729
mod_description=Minecraft Dungeons style click to move, targeting, camera and occlusion fading for NeoForge 1.21.1.
