#!/bin/sh
# Gradle start up script for POSIX generated by Gradle.
app_path=$0
while [ -h "$app_path" ]; do
    APP_HOME=${app_path%"${app_path##*/}"}
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in
      /*) app_path=$link ;;
      *)  app_path=$APP_HOME$link ;;
    esac
done
APP_HOME=$( cd "${app_path%"${app_path##*/}"}" && pwd ) || exit
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi
exec "$JAVACMD" -Xmx64m -Xms64m -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
